practice/config/routes.rb
Rails.application.routes.draw do

  root 'cats#index'

  get '/hugh' => 'cats#index'

  resources :cats do
    resources :achievements
  end

end

practice/app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :cat
end

practice/app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :achievements
end

practice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

practice/app/controllers/cats_controller.rb
class CatsController < ApplicationController


  def index
    @cats = Cat.all
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cats = Cat.all
    respond_to do |format|
      if @cat.save
        format.html {redirect_to root_path}
        format.json {render :json => @cat, :status => :created}
      else
        format.html {render action: 'index'}
        format.json { render :json => root_path.errors.full_messages, :status => :unprocessable_entity}
      end
    end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to root_path
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :breed, :cute)
  end

end

practice/app/helpers/application_helper.rb
module ApplicationHelper
end

practice/app/helpers/cats_helper.rb
module CatsHelper
end

practice/app/views/cats/index.html.erb
<ul id="this_one">
  <% @cats.each do |cat| %>
  <li><a href="/cats/<%=cat.id%>"><%= cat.name %></a>
    <ul><li><%= cat.breed %></li>
        <li>Cute? <%= cat.cute %></li>
    </ul>
  </li>

<% end %>
</ul>

<script id="cat-new" type="text/x-handlebars-template">
  <li><a href="/cats/{{id}}">{{name}}</a>
    <ul>
      <li>
        {{breed}}
      </li>
      <li>
        Cute? {{cute}}
      </li>
    </ul>
  </li>
</script>



<%= form_for @cat do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :breed %>
  <%= f.text_field :breed %>
  <br>
  <br>
  <%= f.label :cute  %>
  <%= f.select :cute, [true, false] %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

practice/app/views/cats/show.html.erb
<ul><%=@cat.name %>
  <li><%= @cat.breed %></li>
  <li><%= @cat.cute %></li>
</ul>

<%= link_to 'Edit Cat', edit_cat_path %>
<%= link_to 'Delete Cat', cat_path, method: :delete %>

practice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>